### ISSUE TITLE
New and alternative way to style the ordered list

### ISSUE THREAD

**Issue by haroun-b** [ironhack-labs/lab-css-recipes-clone#4129]
Hi @ross-u ,

While browsing MDN, I stumbled across a new and simpler way to style `<ol>`s. It isn't as widely supported as the proposed solution, but it's supported well enough to be introduced. So, it would be cool if you guys could add it to the FAQ.

**Implementation:**
```css
  @counter-style custom {
    system: extends decimal;
    suffix: ") ";
  }

  ol {
    list-style: custom;
  }
```

**Docs:** https://developer.mozilla.org/en-US/docs/Web/CSS/@counter-style
